dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
env:
  global:
  - TEST_REPO=manageiq#19330
  - GEM_REPOS=manageiq-providers-ansible_tower#196
script: bundle exec rake test
