dist: xenial
language: ruby
rvm:
- 2.5.7
cache:
  bundler: true
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
matrix:
  fast_finish: true
env:
  global:
  - TEST_REPO=manageiq#19378
  matrix:
  - TEST_REPO=manageiq-api
  - TEST_REPO=manageiq-ui-classic
  - TEST_REPO=manageiq-providers-openshift
  - TEST_REPO=manageiq-providers-kubernetes
