dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
env:
  global:
  - GEM_REPOS=agrare/manageiq-providers-vmware@feature_branch,agrare/vmware_web_service@feature_branch
  - CORE_REPO=agrare/manageiq@feature_branch
script: bundle exec rake test:core
