dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
env:
  global:
  - TEST_REPO=jameswnl/manageiq-providers-ansible_tower@unshare4
  - MANAGEIQ_CORE_REF=7267d03a
script: bundle exec rake test:plugin
