dist: xenial
language: ruby
rvm:
- 2.5.5
cache:
  bundler: true
addons:
  postgresql: '10'
  apt:
    packages:
    - libarchive-dev
matrix:
  fast_finish: true
env:
  global:
    - REPOS=manageiq#20086
  matrix:
    - TEST_REPO=manageiq
    - TEST_REPO=manageiq-api
    - TEST_REPO=manageiq-ui-classic
