name: ManageIQ Cross Repo Workflow

on:
  workflow_call:
    inputs:
      test-repos:
        required: true
        type: string
      repos:
        required: true
        type: string
      test-suite:
        required: false
        type: string
      ruby-version:
        required: false
        type: string
        default: '["2.7"]'
      node-version:
        required: false
        type: string
        default: '["12"]'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-repo: ${{ fromJson(inputs.test-repos) }}
        ruby-version: ${{ fromJson(inputs.ruby-version) }}
        node-version: ${{ fromJson(inputs.node-version) }}
    services:
      postgres:
        image: manageiq/postgresql:10
        env:
          POSTGRESQL_USER: root
          POSTGRESQL_PASSWORD: smartvm
          POSTGRESQL_DATABASE: vmdb_test
        options: --health-cmd pg_isready --health-interval 2s --health-timeout 5s --health-retries 5
        ports:
        - 5432:5432
    env:
      TEST_SUITE: ${{ inputs.test-suite }}
      REPOS: ${{ inputs.repos }}
      TEST_REPO: ${{ matrix.test-repo }}
      PGHOST: localhost
      PGPASSWORD: smartvm
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.manageiq.org/
    - name: Run tests
      run: bundle exec manageiq-cross_repo
